### ISSUE TITLE
The NSG parameter needs to be removed creating the Controller Virtual machines

### ISSUE THREAD

**Issue by blueelvis** [ivanfioravanti/kubernetes-the-hard-way-on-azure#51]
In this section - https://github.com/ivanfioravanti/kubernetes-the-hard-way-on-azure/blob/master/docs/03-compute-resources.md#kubernetes-controllers

This modification also needs to happen in this section - https://github.com/ivanfioravanti/kubernetes-the-hard-way-on-azure/blob/master/docs/03-compute-resources.md#kubernetes-workers

The NSG must be specified for the code to run. Otherwise, the command fails with - 
```
When specifying an existing NIC, do not specify NSG, public IP, ASGs, VNet or subnet.
```

The code should be like below -
```
for i in 0 1 2; do
    echo "[Controller ${i}] Creating public IP..."
    az network public-ip create -n controller-${i}-pip -g kubernetes > /dev/null

    echo "[Controller ${i}] Creating NIC..."
    az network nic create -g kubernetes \
        -n controller-${i}-nic \
        --private-ip-address 10.240.0.1${i} \
        --public-ip-address controller-${i}-pip \
        --vnet kubernetes-vnet \
        --subnet kubernetes-subnet \
        --ip-forwarding \
        --lb-name kubernetes-lb \
        --lb-address-pools kubernetes-lb-pool > /dev/null

    echo "[Controller ${i}] Creating VM..."
    az vm create -g kubernetes \
        -n controller-${i} \
        --image ${UBUNTULTS} \
        --nics controller-${i}-nic \
        --availability-set controller-as \
        --admin-username 'kuberoot' > /dev/null \
        --generate-ssh-keys
done
```

Tested on Windows.

**Comment by ivanfioravanti** [comment]
Could you please try with latest version (1.17.3), upgrading az to the latest version before starting?
Thanks

**Comment by biswarup1290dass** [comment]
I had an issue with the NSG that we are creating here -> https://github.com/ivanfioravanti/kubernetes-the-hard-way-on-azure/blob/master/docs/03-compute-resources.md
and attaching it to the subnet.
Once done with the compute resources setup, I had trouble accessing the controller VMs/WorkerVMs(I had set SSH allow at 100 Priority and HTTPS allow at 101 Priority), and when I removed the NSG from the subnet and attached it to the controller NICs, I was able to SSH. Did I do something wrong due to which I faced the issue? Or shall we revisit the NSG attachment once again. I am not sure what issue to create (assuming  its an issue from my end). So replying to this Issue. cc: @ivanfioravanti .


Az CLI version :

`$ az --version
azure-cli (2.0.55)

acr (2.1.12)
acs (2.3.14)
advisor (2.0.0)
ams (0.3.2)
appservice (0.2.11)
backup (1.2.1)
batch (3.4.1)
batchai (0.4.6)
billing (0.2.0)
botservice (0.1.4)
cdn (0.2.0)
cloud (2.1.0)
cognitiveservices (0.2.4)
command-modules-nspkg (2.0.2)
configure (2.0.20)
consumption (0.4.2)
container (0.3.11)
core (2.0.55)
cosmosdb (0.2.7)
dla (0.2.3)
dls (0.1.7)
dms (0.1.1)
eventgrid (0.2.0)
eventhubs (0.3.2)
extension (0.2.3)
feedback (2.1.4)
find (0.2.13)
hdinsight (0.2.0)
interactive (0.4.1)
iot (0.3.4)
iotcentral (0.1.5)
keyvault (2.2.9)
lab (0.1.5)
maps (0.3.3)
monitor (0.2.8)
network (2.3.0)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.2)
rdbms (0.3.5)
redis (0.3.2)
relay (0.1.2)
reservations (0.4.1)
resource (2.1.8)
role (2.3.0)
search (0.1.1)
security (0.1.0)
servicebus (0.3.2)
servicefabric (0.1.11)
signalr (1.0.0)
sql (2.1.7)
storage (2.3.0)
telemetry (1.0.0)
vm (2.2.12)
`

Python 3.6.6

**Comment by ivanfioravanti** [comment]
I can't reproduce this issue on my side, I'll try again on next "big" version update

**Comment by blueelvis** [comment]
@ivanfioravanti - Yeah, I upgrade my Azure CLI to the latest and still got the issue. Removing the `--nsg ''` parameter helped me proceed ahead with the deployments.

**Comment by ivanfioravanti** [comment]
In latest update pushed it seems everything is working properly
